language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - python setup.py install
script:
    - find ./pyactor -name \*.py -exec pep8 --ignore=E402 {} +
    - nosetests -v --with-coverage --cover-erase --cover-package=pyactor
after_success:
    - pip install coveralls
    - coveralls
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
